### ISSUE TITLE
Add test for ListItemSwipeAction.tsx

### ISSUE THREAD

**Issue by ziedtouibi** [OpenSourceRaidGuild/atom-pwa#55]
Adding test for ListItemSwipeAction.tsx

**Comment by ziedtouibi** [comment]
Hey Guys, @tigerabrodi mentioned that for swipe Interactions it is better to write E2E tests and somehow I agree with him.
PS: I already wrote the the unit test for this component. If you want I can open a PR.

**Comment by mpeyper** [comment]
If you have them written, might as well put the PR up.  We can always choose not to merge it if we decide it's better tested elsewhere.

**Comment by ziedtouibi** [comment]
Done, [PR](https://github.com/OpenSourceRaidGuild/atom-pwa/pull/70) created
