### ISSUE TITLE
Add tests for PeriodicTableTest.tsx

### ISSUE THREAD

**Issue by juhanakristian** [OpenSourceRaidGuild/atom-pwa#81]

**Comment by Aprillion** [comment]
https://github.com/OpenSourceRaidGuild/atom-pwa/projects/1#card-55812402

**Comment by Aprillion** [comment]
@juhanakristian please also have a look at src/components/periodic-table-test/settings/PeriodicTableTestSettings.tsx it possible to together with this one in a single test file

**Comment by juhanakristian** [comment]
I'll be sure to check it out. Thanks @Aprillion 

Currently I'm mocking the settings to make the tests more manageable. I'll make a WIP PR later today.
