### ISSUE TITLE
Combined coverage from Jest+Cypress

### ISSUE THREAD

**Issue by Aprillion** [OpenSourceRaidGuild/atom-pwa#83]
Jest coverage report already looks OK, but some features need to be covered by Cypress (e.g. #82), so it would be nice to combine the coverage reports from both to see the total coverage.

Horus was also interested about combined coverage => https://discord.com/channels/808364903822917662/808364903822917665/817697765072699412

I will try to investigate myself, but I don't promise I will find a good way => feel free to ping me if someone knows how to do it already and this issue is still open 😉

**Comment by Aprillion** [comment]
@mpeyper seemed to have more initial luck trying to do this in parallel => leaving the task up to you ;)

I was not able to generate any coverage report from cypress on my windows machine, it either complained about typescript or not generating any report for me when I tried the steps from official docs and various other stuff from the interned :(

**Comment by Aprillion** [comment]
FTR, the closest I got to making a coverage report from cypress was based on https://github.com/bahmutov/cypress-and-jest#cypress-code-coverage-setup

But I got following cryptic message when I executed `yarn cy:run --spec cypress/integration/smoke.spec.ts`:
```
Error: Error running @cypress/browserify-preprocessor:

You are attempting to preprocess a TypeScript file, but do not have TypeScript configured. Pass the 'typescript' option to enable TypeScript support.
```

WTF does the error even mean?!?

And no more luck with other setup ideas from https://github.com/cypress-io/code-coverage worked for me either 😢

**Comment by mpeyper** [comment]
[For tomorrow](https://discord.com/channels/808364903822917662/808364903822917665/817748934247317564)
